sudo: false

language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - RUSTFLAGS="-C link-dead-code"


script:
  - cargo build --verbose
  - cargo test --verbose
  - ./integration_tests.sh

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
    - libiberty-dev
    - zlib1g-dev
    - kcov

after_success: |
  cargo clean &&
  cargo test --no-run &&
  for file in target/debug/dotfiles_manager-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --merge target/cov target/cov/* &&
  echo "Uploaded code coverage"
